FROM oven/bun:1

WORKDIR /app

# Install dependencies
COPY package.json bun.lock* ./
RUN bun install

# Copy prisma schema
COPY prisma ./prisma

# Copy source code
COPY . .

EXPOSE 3000

CMD ["bun", "run", "start:dev"]

