const institutes = [
  "Abasyn University",
  "Abbottabad University of Science and Technology",
  "Abdul Wali Khan University Mardan",
  "Aga Khan University",
  "Air University",
  "Alhamd Islamic University",
  "Ali Institute of Education",
  "Al-Khair University",
  "Bacha Khan University",
  "Bahauddin Zakariya University",
  "Bahria University",
  "Balochistan University of Engineering and Technology",
  "Balochistan University of Information Technology, Engineering and Management Sciences",
  "Baqai Medical University",
  "Beaconhouse National University",
  "Benazir Bhutto Shaheed University Lyari",
  "CECOS University",
  "City University of Science and Information Technology",
  "Commecs Institute of Business and Emerging Sciences",
  "COMSATS Institute of Information Technology",
  "Dadabhoy Institute of Higher Education",
  "Dawood University of Engineering and Technology",
  "DHA Suffa University",
  "DOW University of Health Sciences",
  "FATA University",
  "Fatima Jinnah Women University",
  "Federal Urdu University of Arts, Sciences and Technology Islamabad",
  "Forman Christian College",
  "Foundation University Islamabad",
  "Gandhara University",
  "Ghazi University",
  "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
  "GIFT University",
  "Global Institute",
  "Gomal University",
  "Government College for Women University, Sialkot",
  "Government College University, Faisalabad",
  "Government College University, Lahore",
  "Government College Women University, Faisalabad",
  "Greenwich University",
  "Habib University",
  "Hajvery University",
  "Hamdard University",
  "Hazara University",
  "HITEC University",
  "Ilma University",
  "Imperial College of Business Studies",
  "Indus University, Pakistan",
  "Indus Valley School of Art and Architecture",
  "Information Technology University",
  "Institute of Business Administration",
  "Institute of Business Management",
  "Institute of Management Sciences",
  "Institute of Southern Punjab",
  "Institute of Space Technology",
  "International Islamic University, Islamabad",
  "Iqra National University",
  "Iqra University",
  "Islamia College Peshawar",
  "Isra University",
  "Jinnah Sindh Medical University",
  "Jinnah University for Women",
  "Karachi Institute of Economics and Technology",
  "Karachi School for Business and Leadership",
  "Karakurum International University",
  "KASB Institute of Technology",
  "Khawaja Freed University of Engineering and Information Technology",
  "Khushal Khan Khattak University",
  "Khyber Medical University",
  "Khyber Pakhtunkhwa Agricultural University",
  "King Edward Medical University",
  "Kinnaird College for Women",
  "Kohat University of Science and Technology",
  "Lahore College for Women University",
  "Lahore Garrison University",
  "Lahore Leads University",
  "Lahore School of Economics",
  "Lahore University of Management Sciences",
  "Lasbela University of Agriculture, Water and Marine Sciences",
  "Liaquat University of Medical and Health Sciences",
  "Mehran University of Engineering and Technology",
  "Minhaj University",
  "Mirpur University of Science and Technology",
  "Mohammad Ali Jinnah University",
  "Mohi-ud-Din Islamic University",
  "Muhammad Nawaz Shareef University of Agriculture, Multan",
  "Muslim Youth University",
  "National College of Arts",
  "National College of Business Administration and Economics",
  "National Defence University",
  "National Textile University",
  "National University of Computer and Emerging Sciences",
  "National University of Modern Languages",
  "National University of Sciences and Technology",
  "Nazeer Hussain University",
  "NED University of Engineering and Technology",
  "Newports Institute of Communications and Economics",
  "Northern University",
  "Nur International University",
  "Pakistan Institute of Development Economics",
  "Pakistan Institute of Engineering and Applied Sciences",
  "Pakistan Institute of Fashion and Design",
  "Peoples University of Medical and Health Sciences for Women",
  "PIMSAT Institute of Higher Education",
  "Pir Mehr Ali Shah Arid Agriculture University",
  "Preston University",
  "Qarshi University",
  "Quaid-e-Awam University of Engineering, Science and Technology",
  "Quaid-i-Azam University",
  "Qurtaba University",
  "Riphah International University",
  "Sardar Bahadur Khan Women's University",
  "Sarhad University of Science and Information Technology",
  "Shah Abdul Latif University",
  "Shaheed Benazir Bhutto City University",
  "Shaheed Benazir Bhutto University",
  "Shaheed Benazir Bhutto University Shaheed Benazirabad",
  "Shaheed Benazir Bhutto Women University",
  "Shaheed Mohtarma Benazir Bhutto Medical University",
  "Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology",
  "Shaheed Zulfiqar Ali Bhutto University of Law",
  "Shifa Tameer-e-Millat University",
  "Sindh Agriculture University",
  "Sindh Madresatul Islam University",
  "Sir Syed University of Engineering and Technology",
  "Sukkur Institute of Business Administration",
  "Superior Group of Colleges",
  "Textile Institute of Pakistan",
  "The Government Sadiq College Women University, Bahawalpur",
  "The Institute of Management Sciences",
  "The Islamia University of Bahawalpur",
  "The University of Faisalabad",
  "The University of Lahore",
  "The University of Poonch",
  "The Women University, Multan",
  "University of Agriculture, Faisalabad",
  "University of Azad Jammu and Kashmir",
  "University of Balochistan",
  "University of Central Punjab",
  "University of Education",
  "University of Engineering and Technology, Lahore",
  "University of Engineering and Technology, Peshawar",
  "University of Engineering and Technology, Taxila",
  "University of Gujrat",
  "University of Haripur",
  "University of Health Sciences, Lahore",
  "University of Karachi",
  "University of Kotli Azad Jammu and Kashmir",
  "University of Loralai",
  "University of Malakand",
  "University of Management and Technology",
  "University of Peshawar",
  "University of Sargodha",
  "University of Science and Technology, Bannu",
  "University of Sindh",
  "University of South Asia",
  "University of Swabi",
  "University of Swat",
  "University of the Punjab",
  "University of Turbat",
  "University of Veterinary and Animal Sciences",
  "University of Wah",
  "Women University of Azad Jammu and Kashmir Bagh",
  "Ziauddin University",
];

export async function seedInstitutes(prisma) {
  console.log('🌱 Seeding institutes...');
  let created = 0;
  let skipped = 0;
  for (const name of institutes) {
    try {
      const existing = await prisma.institute.findFirst({ where: { name } });
      if (existing) { skipped++; continue; }
      await prisma.institute.create({ data: { name, status: 'active' } });
      created++;
    } catch (error) {
      console.error(`Error seeding institute "${name}":`, error.message);
    }
  }
  console.log(`✅ Institutes seeding completed: ${created} created, ${skipped} skipped`);
  return { created, skipped };
}
