import { IsEnum, IsOptional, IsString, IsUUID } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export enum AccountRoleKey {
  // Purchases
  PURCHASES_LOCAL = 'PURCHASES_LOCAL',
  PURCHASES_IMPORT = 'PURCHASES_IMPORT',
  PURCHASES_CONSIGNMENT = 'PURCHASES_CONSIGNMENT',
  PURCHASES_RETURN = 'PURCHASES_RETURN',

  // Supplier / AP
  ADVANCE_TO_SUPPLIERS = 'ADVANCE_TO_SUPPLIERS',
  AP_PARTIES = 'AP_PARTIES',

  // Sales / AR
  SALES_REVENUE_RETAIL = 'SALES_REVENUE_RETAIL',
  SALES_REVENUE_WHOLESALE = 'SALES_REVENUE_WHOLESALE',
  ACCOUNTS_RECEIVABLE = 'ACCOUNTS_RECEIVABLE',
  ADVANCE_FROM_CUSTOMERS = 'ADVANCE_FROM_CUSTOMERS',
  SALES_RETURN_RETAIL = 'SALES_RETURN_RETAIL',
  SALES_RETURN_WHOLESALE = 'SALES_RETURN_WHOLESALE',

  // Tax
  SALES_TAX_PAYABLE_FEDERAL = 'SALES_TAX_PAYABLE_FEDERAL',
  SALES_TAX_PAYABLE_PROVINCIAL = 'SALES_TAX_PAYABLE_PROVINCIAL',
  INPUT_TAX_RECOVERABLE = 'INPUT_TAX_RECOVERABLE',
  WHT_SALARY = 'WHT_SALARY',
  WHT_GOODS = 'WHT_GOODS',
  WHT_SERVICES = 'WHT_SERVICES',

  // Payroll — Admin dept (70xxxxx)
  SALARIES_EXPENSE_ADMIN = 'SALARIES_EXPENSE_ADMIN',
  EOBI_EXPENSE_ADMIN = 'EOBI_EXPENSE_ADMIN',
  PF_EXPENSE_ADMIN = 'PF_EXPENSE_ADMIN',

  // Payroll — Selling dept (80xxxxx)
  SALARIES_EXPENSE_SELLING = 'SALARIES_EXPENSE_SELLING',
  EOBI_EXPENSE_SELLING = 'EOBI_EXPENSE_SELLING',
  PF_EXPENSE_SELLING = 'PF_EXPENSE_SELLING',

  // Payroll — Shared payable accounts (Cr side)
  AP_SALARIES = 'AP_SALARIES',
  AP_EOBI = 'AP_EOBI',
  AP_PROVIDENT_FUND = 'AP_PROVIDENT_FUND',
  AP_SESSI = 'AP_SESSI',
  AP_SALARIES_FINAL_SETTLEMENT = 'AP_SALARIES_FINAL_SETTLEMENT',

  // Inventory / Stock
  STOCK_IN_TRADE_WAREHOUSE = 'STOCK_IN_TRADE_WAREHOUSE',
  STOCK_IN_TRADE_STORES = 'STOCK_IN_TRADE_STORES',
  COST_OF_GOODS_SOLD = 'COST_OF_GOODS_SOLD',
  STOCK_ADJUSTMENTS = 'STOCK_ADJUSTMENTS',
  INVENTORY_SHORTAGE = 'INVENTORY_SHORTAGE',

  // POS — Payment methods
  CASH_IN_HAND = 'CASH_IN_HAND',
  BANK_MERCHANT = 'BANK_MERCHANT',

  // POS — Vouchers & Loyalty
  CREDIT_VOUCHERS = 'CREDIT_VOUCHERS',
  GIFT_VOUCHERS = 'GIFT_VOUCHERS',
  GIFT_VOUCHERS_CORPORATE = 'GIFT_VOUCHERS_CORPORATE',
  CLAIM_VOUCHERS = 'CLAIM_VOUCHERS',
  EXCHANGE_VOUCHERS = 'EXCHANGE_VOUCHERS',
  ALLIANCE_REWARD = 'ALLIANCE_REWARD',

  // POS — Fees & Charges
  POS_INTEGRATION_FEE_PAYABLE = 'POS_INTEGRATION_FEE_PAYABLE',
  POS_INTEGRATION_FEE_EXPENSE = 'POS_INTEGRATION_FEE_EXPENSE',
  BANK_COMMISSION_SELLING = 'BANK_COMMISSION_SELLING',
  BANK_COMMISSION_ADMIN = 'BANK_COMMISSION_ADMIN',

  // POS — Cash management
  CASH_SHORTAGE_OVERAGE = 'CASH_SHORTAGE_OVERAGE',

  // Financial charges
  BANK_CHARGES = 'BANK_CHARGES',
  MARKUP_ON_LOAN = 'MARKUP_ON_LOAN',
  BANK_CHARGES_IMPORT = 'BANK_CHARGES_IMPORT',
  EXCHANGE_LOSS_IMPORT = 'EXCHANGE_LOSS_IMPORT',
}

export class UpsertFinanceAccountConfigDto {
  @ApiProperty({ enum: AccountRoleKey })
  @IsEnum(AccountRoleKey)
  key: AccountRoleKey;

  @ApiProperty({ description: 'ChartOfAccount ID to map to this role' })
  @IsUUID()
  accountId: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  description?: string;
}

export class BulkUpsertFinanceAccountConfigDto {
  @ApiProperty({ type: [UpsertFinanceAccountConfigDto] })
  configs: UpsertFinanceAccountConfigDto[];
}
